### ISSUE TITLE
Support macro set-up moves

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#106]
```
Similar to the same MC7D feature, allow for the recording of set-up moves 
before macro applications with automatic reversing of set-up moves after macro 
application.

This can be thought of as a special type of label inserted into the history 
during normal use such that all twists after that point and before the next 
macro application are taken to be set-up moves that will be done in reverse 
after completion of the macro application.
```

Original issue reported on code.google.com by `cutelyaw...@gmail.com` on 11 Jan 2011 at 9:18

**Comment by cutelyaware** [comment]
Implemented in v4.1 commit 82c5bb72a67a7447a9b6376a2be09d0aee4e2ce1.
Usage: Macros > Begin Macro Setup Moves (<ctrl>b) inserts a history mark and enters a new mode (yellow sky) until either canceled or a macro is applied. After a macro is applied, the reverse of the setup moves up to that point are applied and the mark is removed. Repeat selections of this command simply reset the mark to the current point. Undo/redo still function properly in this mode though undoing past the setup mark cancels the setup.
