### ISSUE TITLE
Add a blindfolded solving option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#107]
```
Blindfolded solutions can be done by studying and then saving a scrambled 
state, closing MC4D, putting a face_colors file in place in which all faces are 
gray, and then restarting MC4D. That is obviously awkward. A better way to 
support this would be a simple checkbox toggle that turns all face colors to 
gray when checked and restores them when unchecked.

```

Original issue reported on code.google.com by `cutelyaw...@gmail.com` on 11 Jan 2011 at 9:22

**Comment by cutelyaware** [comment]
Implemented in commit da29063c5f57017a1e673cb2cd21b561d0519243.
Although the ideal UI might delay the solve fanfare until the user unblinds the puzzle, that would require supporting a new "fanfare pending" mode. My solution was to leave the fanfare implementation alone and automatically unblind at the same time. Not quite what Nan suggested, but hopefully makes up for that with what should be a pleasant surprise.

Note the following commit (da29063c5f57017a1e673cb2cd21b561d0519243) displays the keyboard shortcut in the checkbox's tooltip.
