### ISSUE TITLE
Android app, lack of log

### ISSUE THREAD

**Issue by hacker4765** [cutelyaware/magiccube4d#117]
I have been dismayed at the lack of log in the app unfortunately my current situation does not allow me to use the same pc long enough to solve a 4d Rubik cube. I would greatly appreciate that addition all features or if that feature all ready exist a more accessible explanation anywere, having the explanation on the google play store page would be great but even having it in the wiki would be a great addition for the very small group of people who would use this feature.

**Comment by cutelyaware** [comment]
This project is the desktop version but the issue you are reporting is for the Android project. Please open a feature request here: https://github.com/cutelyaware/MC4D, thanks!
