### ISSUE TITLE
Macros with some reference sticker patterns produce broken results

### ISSUE THREAD

**Issue by Tekeur** [cutelyaware/magiccube4d#120]
I've been having two issues when I try to create a Macro that seem to be directly linked to the choice of the reference stickers at the beginning:

-Sometimes a specific twist will always get skipped, but other twists in the macros will get executed just fine (On the file I have attached it is the case for macro 1, 2 and 3)
-The macro doesn't apply itself when a specific twist is in it (macro 4 in the file I have attached)

The specific twist I mentionned seems to depend on the position of the reference stickers, and I have found some choices of reference stickers that have no issues.

(If needed I can provide screenshots showing which pieces are the references pieces for the macros in my attached file)

Version: 4.0.185 on Windows 10
[macros.zip](https://github.com/cutelyaware/magiccube4d/files/72481/macros.zip)

**Comment by cutelyaware** [comment]
Yes, please attach a snap or diagram or description of your reference sticker pattern.

**Comment by Tekeur** [comment]
Ok, I attached a .zip with screenshots showing the patterns and a new macro file (I had to change the macro file because I forgot the patterns on the first one) .
[Macros+References.zip](https://github.com/cutelyaware/magiccube4d/files/72532/Macros.References.zip)

**Comment by cutelyaware** [comment]
What it looks like so far is that you've somehow managed to get the very center sticker of a face into the macro moves which is illegal and therefore should be impossible. Can you also show me which twist stickers you clicked in one of your broken macros? I need to be able to reproduce the full process.

**Comment by Tekeur** [comment]
I wasn't aware that center stickers weren't meant to be reference stickers, my macro was supposed to permute those center stickers so it made sense to choose them. However, as you can see on macro '2' and '3' the same issue is happening with edges and corners as reference stickers and no center stickers are involved. Here I have highlighted the twist sticker I used in all 4 macros: http://img15.hostingpics.net/pics/890212Sticker.png (Everything is oriented the same was as on my previous screenshots)

The first three macros only consists of that move, but I added two random moves on the fourth one to show that it doesn't execute at all.

**Comment by cutelyaware** [comment]
It should be fine to use 1-color pieces as reference stickers. I meant that it appears that you got a central sticker into the twist sequence which should be impossible. Your image allowed me to reproduce a non-functional macro so I should be able to dig into it. Can't promise anything though. Thanks for your help.

**Comment by Tekeur** [comment]
Ok, thanks for the quick replies ! In the meantime I found that those reference stickers cause no issues so I'm using them for all my macros: http://img15.hostingpics.net/pics/483369450.png .

Also my .log file just got corrupted (It says "Failed to parse" ), I'm not sure what caused this so I don't know if I should open a issue for this . (I guess I'll just make backups now)

**Comment by cutelyaware** [comment]
I'm sure you can work around the problem since it's not come up before 
now so it must be rare, but I would like to fix it. If you want to 
choose a standard reference pattern, I suggest choosing stickers on 
unique cubies. Your stickers #2 and #3 are on the same piece (or 
collinear). It may not matter but it will be slightly safer.

Regarding your corrupt log file, please send it to me directly at 
melinda@superliminal.com and I'll take a look. Thanks!

**Comment by Tekeur** [comment]
Thanks for the tips ! Yes it's probably rare, and all my macros are working just fine right now after I changed the reference stickers. 
As for the log file I was about to send it when I realized it was empty, not sure how it happened but it doesn't really matter as I have moved on to another solve since then.

**Comment by cutelyaware** [comment]
Glad to know you're not stuck on anything. Let me know if you submit any solutions.

**Comment by cutelyaware** [comment]
Burkard Polster also hit this bug using a small L pattern starting with a 2D face center, ending on an adjacent face center, and a middle sticker which is the edge piece adjacent to both. He made a little video of the problem here https://youtu.be/4rDO58OLhpc

**Comment by cutelyaware** [comment]
For reference, applying a broken macro injects bad data into the history. No exceptions are thrown at that time but subsequent operations such as Reset (ctrl-0) throw exceptions like the following:

java.lang.IllegalArgumentException: applyTwistToState called on gripIndex 26 which does not rotate!
	at com.superliminal.magiccube4d.PolytopePuzzleDescription.applyTwistToState(PolytopePuzzleDescription.java:1357)
	at com.superliminal.magiccube4d.MC4DSwing.syncPuzzleStateWithHistory(MC4DSwing.java:1293)
	at com.superliminal.magiccube4d.MC4DSwing.cancel(MC4DSwing.java:165)
	at com.superliminal.magiccube4d.MC4DSwing.access$4(MC4DSwing.java:154)
	at com.superliminal.magiccube4d.MC4DSwing$16.actionPerformed(MC4DSwing.java:549)

**Comment by cutelyaware** [comment]
I just want to call attention to Tekeur's third image in which the reference sticker's plane does not cut a face center.
![brokenmacro3](https://cloud.githubusercontent.com/assets/838809/15595567/131a4634-2375-11e6-9618-a86ac36e363e.png)

**Comment by roice3** [comment]
The problem here was that the reference points (3 clicked + 1 implicit)
could be coplanar, which isn't enough to uniquely transform the macro
later.  So we disallow selecting reference points that are coplanar.
