### ISSUE TITLE
Macro with different orientations

### ISSUE THREAD

**Issue by gellyfisher** [cutelyaware/magiccube4d#122]
Hi, I currently have 2 macros. I use the first, rotate the hypercube, then I use the second. Now I would like to put this together into another macro, but sadly this is not possible because when I try it the second macro gets executed with the same orientation as the first and I am unable to change the orientationwhile recording a macro.

**Comment by cutelyaware** [comment]
Normal rotations are not twists--they only affect the view--however you can perform a twist that has the effect of rotating the whole puzzle by holding down all of the number keys for your puzzle size and then doing a click twist which will move all slices. So for the standard 3^4, you hold down the 1, 2 & 3 keys. This should do what you want. Play with different combinations of number keys to see how this works if you have not used the slice mask before. It is a powerful feature.
