### ISSUE TITLE
Not recognizing solved state when last move is macro

### ISSUE THREAD

**Issue by programagor** [cutelyaware/magiccube4d#124]
When solving a 5^4, my last move was a macro for corner (4c piece) orientation. However, upon reaching the solved state, no message appeared. When I did and undid one dummy twist, nothing happened. After I made 4 dummy twists in the same direction, the solved state was recognised and fanfares played.
This suggests that the puzzle is not checked for solvedness at the end of (and probably during) macro execution.

**Comment by cutelyaware** [comment]
Resolved at dada606.
