### ISSUE TITLE
Colours from facecolors.txt overlap different puzzles with the same number of cells

### ISSUE THREAD

**Issue by Sonicpineapple** [cutelyaware/magiccube4d#130]
The colours I've added to puzzles using facecolors.txt are set up to have similar colours opposite, but there is no way to tell MC4D to use two different colour schemes for two different puzzles. For example, {6}x{4} and {5}x{5} read the same line of colours, but while this produces what I wanted on the {6}x{4}, the {5}x{5} is a mess, which makes solving unpleasant. Perhaps adding the puzzle's schlafli symbol at the front of the colour line?

**Comment by cutelyaware** [comment]
It's a reasonable request though it's so specific that it's unlikely to be implemented.

**Comment by roice3** [comment]
Addressed by @Sonicpineapple pull request.
