### ISSUE TITLE
Does it work with Lenovo Ideapad 33OS?

### ISSUE THREAD

**Issue by SpiritusTerra** [cutelyaware/magiccube4d#133]
I couldn't get the jar file to work. Every download was the same. I opened it, then it asked me if I want it to make changes to the device. (Yes) Then it did nothing. I also clicked the link. Am I doing it wrong?

**Comment by SharkRetriever** [comment]
Hi Spiritus, what OS are you on?

**Comment by SpiritusTerra** [comment]
My OS is (I believe) Intel CORE i3 8th Gen

**Comment by SharkRetriever** [comment]
OS usually refers to something like Windows, Mac, or Linux. 
Are you on some version of Windows, and if so, which version?

I'm also guessing after downloading the jar file you tried double-clicking it and nothing showed up.
Maybe try using the command line and running
`java.exe -jar [name-of-download-file].jar`

**Comment by SpiritusTerra** [comment]
Oh, then my OS is Windows. It dosen't matter now though, as I accidentally killed my computer.

**Comment by SharkRetriever** [comment]
Alright. @cutelyaware I think we should close this issue.
