### ISSUE TITLE
View rotations of stickers to center not displaying intuitively.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#22]
```
I'm talking of the ctrl-click feature here.  The fact that Don did this per-
sticker is awesome!

It took me a while to figure out why it wasn't behaving quite as expected for 
stickers that were not at the centers of cells (e.g. 1C stickers).  The 
weirdness is that that projection of non-cental stickers makes them look as 
if they haven't actually moved to the "center".  This could be fixed if the 
rotation code paid attention to the shrink parameters.
```

Original issue reported on code.google.com by `roi...@gmail.com` on 19 Sep 2009 at 6:04

**Comment by donhatch** [comment]
The intent is to center an element of the polytope (i.e. cell, 2-face, edge, or vertex), not the sticker-- I understand the confusion, but I can't think of a better way to do it, given that stickers are the only thing of substance available to click on.

I don't have the feeling that centering a sticker would give a very nice view... it usually wouldn't be very symmetric, and of course when faceshrink changes, the sticker would no longer be centered.

BTW I notice the ui calls it "by Cubie" - this happens to be correct for edgelength-3 puzzles, but is misleading for other puzzles.  Perhaps that's fine.  An alternative might be to call it "by Element" and then maybe have a tooltip elaborating on what "Element" means.  An explanatory tooltip might be helpful in any case.

Roice, Melinda, is there anything you think should be done here?

**Comment by roice3** [comment]
I'm good with closing this one myself.

(I'm not much worried about either of the two concerns expressed here: the original thought or the "Cubie" v. "Element" naming.)
