### ISSUE TITLE
Twist count can increase during an automatic solve.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#66]
```
(1) Make a Macro
(2) Reset the Puzzle
(3) Apply the Macro
(4) Click Solve (Cheat)

The twist counts actually start increasing.

```

Original issue reported on code.google.com by `roi...@gmail.com` on 27 Oct 2009 at 5:20

**Comment by cutelyaware** [comment]
Fixed in v4.1 commit 1e33ac0b59255978a439a5d59fe81629a06497fc. Stripping of all marks at the beginning of an automated solve allows inverse moves to undo their corresponding twists when separated by marks such as macro close ']' and scramble boundary '|'.
