### ISSUE TITLE
Make some icon for the program

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#69]
```
Default .jar icon is not presenting very well. 
```

Original issue reported on code.google.com by `Remigius...@gmail.com` on 27 Oct 2009 at 8:05

**Comment by cutelyaware** [comment]
Seems to be impossible, sorry. Best you can do is change it manually on the particular machine and even that's platform specific. For Windows, here's some info: https://community.oracle.com/thread/1301514
