### ISSUE TITLE
Incorporate Don's latest puzzle generation engine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#94]
```
Hopefully we can more or less just drop in his implementation and fold in
Roice's improvements. I expect it will be a little more complicated than
that, but Don thinks it won't be bad.
```

Original issue reported on code.google.com by `cutelyaw...@gmail.com` on 20 Nov 2009 at 7:50

**Comment by donhatch** [comment]
Apologies for the Rip Van Winkle act.
I made a pull request that I think addresses this issue: https://github.com/cutelyaware/magiccube4d/pull/135

**Comment by cutelyaware** [comment]
Woo hoo! Big milestone today. So satisfying to finally see it happen! Thanks so much Don!!! ❤️

**Comment by donhatch** [comment]
Note that this has now been reverted, in ecfc8c1d8ba89dacabf4fd2fa8b08ec68130d92e.
I'm leaving this issue closed since I assume this will never happen.
